#!perl

use strict;
use warnings;

use Cpanel::JSON::XS qw( decode_json );
use DBIx::Norm ();

my $source = shift @ARGV;
my $values  = $ARGV[0] ? decode_json( shift @ARGV) : undef;
my $where  = $ARGV[0] ? decode_json( shift @ARGV) : undef;

my $query = DBIx::Norm->new->update( $source, $values, $where );

print $query->do_as_sql;

exit(0);

=head1 SYNOPSIS

    perl -Ilib script/update customer '{ "name" : "Robert" }' '{ "last_name": "Smith"}'

prints:

    $dbh->selectall_arrayref(
        <<'SQL', { Slice => {} },  );
    SELECT count(*) FROM log WHERE ( created_at IS NOT NULL )
    SQL

=cut

# PODNAME: select
